import { getAvailablesTiles } from './Available';

describe('getAvailablesTiles', () => {
  it('should handle the one at x=4 and y=4', () => {
    expect(
      getAvailablesTiles([
        [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
        [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
        [
          {},
          {},
          {},
          { isLand: true },
          { isLand: true },
          { isLand: true },
          {},
          {},
          {},
          {},
        ],
        [
          {},
          {},
          { isLand: true },
          { isLand: true },
          { isLand: true },
          { isLand: true },
          { isLand: true },
          {},
          {},
          {},
        ],
        [
          {},
          {},
          { isLand: true },
          { isLand: true },
          { isLand: true },
          { isLand: true },
          { isLand: true },
          {},
          {},
          {},
        ],
        [
          {},
          {},
          { isLand: true },
          { isLand: true },
          { isLand: true },
          { isLand: true },
          { isLand: true },
          {},
          {},
          {},
        ],
        [{}, {}, {}, {}, { isLand: true }, {}, {}, {}, {}, {}],
        [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
        [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
        [{}, {}, {}, {}, {}, {}, {}, {}, {}, {}],
      ])
    ).toEqual([
      { x: 2, y: 2 },
      { x: 1, y: 3 },
      { x: 1, y: 5 },
      { x: 1, y: 4 },
      { x: 2, y: 6 },
      { x: 2, y: 1 },
      { x: 3, y: 1 },
      { x: 3, y: 7 },
      { x: 2, y: 7 },
      { x: 4, y: 1 },
      { x: 4, y: 7 },
      { x: 5, y: 1 },
      { x: 6, y: 2 },
      { x: 6, y: 3 },
      { x: 6, y: 5 },
      { x: 6, y: 6 },
      { x: 5, y: 7 },
      { x: 7, y: 4 },
    ]);
  });
});
